// Vanilla renderer for the AI Search Readiness tool. No framework, no build.
// All text taken from the analyzed page is escaped before it touches innerHTML.

import { metal } from './metal.js';

const $ = (sel) => document.querySelector(sel);

const esc = (s) =>
  String(s ?? '').replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
  );

const ICONS = {
  pass: '<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/>',
  warn: '<path d="M12 9v4M12 17h.01"/><path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0Z"/>',
  fail: '<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6M9 9l6 6"/>',
  info: '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/>',
};

const statusIcon = (status) =>
  `<svg class="check-icon i-${status}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">${ICONS[status] || ICONS.info}</svg>`;

const EV_LABEL = {
  official: 'Official docs',
  study: 'Study',
  opinion: 'Vendor view',
  experimental: 'Experimental',
};

const evidenceBadge = (ev) =>
  `<a class="badge-ev ev-${ev.type}" href="${esc(ev.url)}" target="_blank" rel="noopener noreferrer">${EV_LABEL[ev.type]}<span class="src">&middot; ${esc(ev.source)}</span></a>`;

const READ_LABEL = {
  official: 'Read the guidance',
  study: 'See the study',
  opinion: 'Read the guide',
  experimental: 'See the docs',
};

const sourceLink = (ev) =>
  `<a class="read-more" href="${esc(ev.url)}" target="_blank" rel="noopener noreferrer">${READ_LABEL[ev.type]} at ${esc(ev.source)}<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10"/></svg></a>`;

const evidenceRow = (ev) => `<div class="ev-row">${evidenceBadge(ev)}</div>`;

const sswLink = (ssw) =>
  `<a class="ssw-link" href="${esc(ssw.url)}" target="_blank" rel="noopener noreferrer" title="SSW Rule: ${esc(ssw.title)}">Read the SSW rule<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10"/></svg></a>`;

const STATUS_WORD = { pass: 'PASS', warn: 'WARN', fail: 'FAIL', info: 'INFO' };

const buildMarkdown = (report) => {
  const out = [
    `# AI Search Readiness — ${report.finalUrl}`,
    '',
    `**Score: ${report.overall}/100 (Grade ${report.grade})** — ${report.passCount}/${report.totalScored} checks passed.`,
    '_Generated by the TinaCMS AI Search Readiness checker (tina.io). Fixes and sources included below._',
    '',
  ];
  for (const cat of report.categories) {
    out.push(`## ${cat.title} — ${cat.score}/100`, '');
    for (const ch of cat.checks) {
      out.push(`- **[${STATUS_WORD[ch.status]}] ${ch.label}** — ${ch.detail}`);
      if (ch.status !== 'pass') {
        out.push(`  - Fix: ${ch.fix}`);
      }
      out.push(`  - Why: ${ch.why}`);
      out.push(`  - Source (${ch.evidence.type}): ${ch.evidence.source} — ${ch.evidence.url}`);
    }
    out.push('');
  }
  return out.join('\n');
};

const agentFeature = (report) => `
  <section class="agent-feature reveal">
    <canvas class="agent-metal" aria-hidden="true"></canvas>
    <div class="agent-feature-text">
      <span class="agent-eyebrow">
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m12 3-1.9 5.8a2 2 0 0 1-1.3 1.3L3 12l5.8 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.8a2 2 0 0 1 1.3-1.3L21 12l-5.8-1.9a2 2 0 0 1-1.3-1.3Z"/></svg>
        Made for your AI
      </span>
      <h2>You&rsquo;re going to paste this into your AI anyway</h2>
      <p>Grab the whole report as Markdown, every check, its fix and its source, ready to drop into ChatGPT, Claude or your coding agent.</p>
      <button class="btn" type="button" id="copy-md">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect width="14" height="14" x="8" y="8" rx="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
        Copy report as Markdown
      </button>
    </div>
    <div class="agent-code" aria-hidden="true">
      <div class="agent-code-bar"><i></i><i></i><i></i><em>ai-search-readiness.md</em></div>
      <pre id="md-pre"></pre>
    </div>
  </section>`;

const checkRow = (check) => `
  <div class="check" id="check-${check.id}">
    <button class="check-btn" type="button">
      ${statusIcon(check.status)}
      <span class="check-main">
        <span class="check-title">
          <span>${esc(check.label)}</span>
          <svg class="chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>
        </span>
        <span class="check-detail">${esc(check.detail)}</span>
      </span>
    </button>
    <div class="check-body">
      <div class="box">
        <p><strong>Fix:</strong> ${esc(check.fix)}</p>
        <p><strong>Why it matters:</strong> ${esc(check.why)}</p>
        <div class="link-row">
          <span class="lr-left">${evidenceBadge(check.evidence)}</span>
          ${check.ssw ? sswLink(check.ssw) : ''}
        </div>
      </div>
    </div>
  </div>`;

const category = (cat) => `
  <section class="card category reveal">
    <header class="cat-head">
      <div>
        <h3>${esc(cat.title)}</h3>
        <p>${esc(cat.blurb)}</p>
      </div>
      <div class="cat-score">${cat.score}<small>/ 100</small></div>
    </header>
    <div class="checks">${cat.checks.map(checkRow).join('')}</div>
  </section>`;

const TOOLS = [
  ['Google Rich Results Test', 'https://search.google.com/test/rich-results', 'Validate your structured data against Google itself.'],
  ['PageSpeed Insights / Lighthouse', 'https://pagespeed.web.dev/', 'Core Web Vitals and the experimental agentic-browsing audits.'],
  ['Schema Markup Validator', 'https://validator.schema.org/', 'Check your JSON-LD parses and matches your content.'],
  ['Semrush', 'https://www.semrush.com/', 'Full site audits, keyword and AEO tracking (paid).'],
];

const fullReport = (report) => `
  <div class="report">
    ${agentFeature(report)}
    <div class="report-cats">
      <section class="read-yourself reveal">
        <h3>If you&rsquo;d rather read it yourself</h3>
      </section>
      ${report.categories.map(category).join('')}
    </div>
    <section class="next reveal">
      <h3>Where to go next</h3>
      <p style="color:var(--text-2);font-size:0.875rem;margin-top:0.25rem;">This is a static, single-page check. To go deeper, these tools pick up where it stops.</p>
      <div class="tool-grid">
        ${TOOLS.map(
          ([name, href, note]) => `<a class="tool" href="${href}" target="_blank" rel="noopener noreferrer">
            <span><span class="name">${esc(name)}</span><span class="note">${esc(note)}</span></span>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><path d="M15 3h6v6M10 14 21 3"/></svg>
          </a>`,
        ).join('')}
      </div>
      <details class="refs">
        <summary>Sources &amp; further reading</summary>
      <ul>
        <li>${evidenceRow({ type: 'study', source: "GEO, Aggarwal et al. (KDD '24)", url: 'https://arxiv.org/abs/2311.09735' })}
          <p>In a controlled benchmark, adding <strong>citations</strong>, <strong>statistics</strong> and <strong>quotations</strong> improved a source&rsquo;s visibility in AI-generated answers by roughly <strong>30 to 40%</strong> (best single method +41%), tested on GPT-3.5-class engines and Perplexity. The same study found <strong>keyword stuffing did nothing</strong>. One study from 2023-24, so treat it as directional, not a traffic guarantee.</p></li>
        <li>${evidenceRow({ type: 'official', source: 'Google Search Central', url: 'https://developers.google.com/search/docs/appearance/ai-features' })}
          <p>Google states there are <strong>no special requirements</strong>, no AI-specific schema, and no machine-readable AI files needed to appear in AI Overviews. A page just has to be indexable and snippet-eligible.</p></li>
        <li>${evidenceRow({ type: 'experimental', source: 'Chrome Lighthouse, agentic browsing', url: 'https://developer.chrome.com/docs/lighthouse/agentic-browsing/scoring' })}
          <p>Lighthouse&rsquo;s agentic-browsing checks are experimental and reported as pass/fail, not a 0-100 score. It reports whether an <code>llms.txt</code> exists, but that file has <strong>no confirmed effect</strong>: Google has said it ignores it, so we score it as informational only.</p></li>
      </ul>
      </details>
    </section>
  </div>`;

const topFixes = (report) => {
  if (!report.topFixes.length) {
    return `<div class="card reveal" style="padding:1.5rem;background:var(--seafoam-100);color:var(--seafoam-800);">Nothing critical to fix. Every scored check passed. Unlock the full report below to see the detail and evidence.</div>`;
  }
  return `<div class="fixes reveal">
    <h3>Your 3 highest-impact fixes</h3>
    <ul class="fix-list">
      ${report.topFixes
        .map(
          (f, i) => `<li class="fix-item">
        <span class="fix-num">${i + 1}</span>
        <span><span class="lbl">${esc(f.label)}</span><span class="why">${esc(f.why)}</span>${sourceLink(f.evidence)}</span>
      </li>`,
        )
        .join('')}
    </ul>
  </div>`;
};

const leadGate = (report) => `
  <div class="gate reveal" id="gate">
    <div class="peek" aria-hidden="true"><span style="width:66%"></span><span style="width:50%"></span><span style="width:75%"></span><span style="width:40%"></span></div>
    <div class="inner">
      <span class="lock"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect width="18" height="11" x="3" y="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg></span>
      <h3>See your full report</h3>
      <p>Unlock all ${report.totalScored} checks with the exact fix and the evidence behind each one, plus where to go next. We&rsquo;ll email you a copy.</p>
      <form id="lead-form">
        <input type="email" id="lead-email" placeholder="you@company.com" aria-label="Your email" />
        <button class="btn" type="submit" id="lead-btn">Unlock report</button>
      </form>
      <p class="error hidden" id="lead-error"></p>
      <p class="microcopy">No spam. Unsubscribe anytime.</p>
    </div>
  </div>`;

// --- score reveal (replaces the loading spinner + summary card) ---------------

// Metal-masked number: a metal canvas masked to the digits. The site font
// (IBM Plex) is embedded into the mask SVG — web fonts don't otherwise load
// inside an SVG used as a CSS mask.
let maskFontCss = '';
const maskFontReady = fetch('/fonts/IBMPlexSans-SemiBold.woff2')
  .then((r) => r.arrayBuffer())
  .then((buf) => {
    let bin = '';
    const bytes = new Uint8Array(buf);
    for (let i = 0; i < bytes.length; i++) {
      bin += String.fromCharCode(bytes[i]);
    }
    maskFontCss = `@font-face{font-family:'PlexMask';src:url(data:font/woff2;base64,${btoa(bin)}) format('woff2')}`;
  })
  .catch(() => {});

const scoreMaskUri = (n) => {
  const t = String(n);
  const H = 100;
  const W = t.length * 54 + 18;
  const style = maskFontCss ? `<style>${maskFontCss}</style>` : '';
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${W} ${H}'><defs>${style}</defs><text x='${W / 2}' y='${H * 0.54}' text-anchor='middle' dominant-baseline='central' font-family='PlexMask, "IBM Plex Sans", Arial, sans-serif' font-weight='600' font-size='${H * 0.9}' fill='#fff'>${esc(t)}</text></svg>`;
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
};

// Set both prefixed and unprefixed mask props (Safari still needs -webkit-).
const setMask = (el, image, size, position) => {
  el.style.maskImage = image;
  el.style.webkitMaskImage = image;
  el.style.maskSize = size;
  el.style.webkitMaskSize = size;
  el.style.maskPosition = position;
  el.style.webkitMaskPosition = position;
  el.style.maskRepeat = 'no-repeat';
  el.style.webkitMaskRepeat = 'no-repeat';
};

// The stats list starts at max-width 0 (zero footprint) so the disc sits
// dead-centre while loading; on load it eases out to its measured width and
// the flex row re-centres the whole group, sliding the disc left smoothly.
// Then the disc fades out to the metal-masked number, and an ink layer inside
// the same mask slowly fades the metal to black.
const bigScoreShell = () => `
  <div class="big-score loading" id="big-score">
    <div class="big-score-metal" id="score-metal">
      <div class="bs-num" id="bs-num">
        <div class="bs-num-in"><canvas></canvas><i class="bs-ink"></i></div>
      </div>
      <div class="bs-disc"><canvas></canvas></div>
    </div>
    <ul class="big-stats" id="big-stats"></ul>
  </div>`;

// --- interaction --------------------------------------------------------------

const results = $('#results');

// Scroll-triggered fade-ins. Elements with .reveal start hidden (only when JS is
// present, via .reveal-enabled) and animate in as they enter the viewport.
document.documentElement.classList.add('reveal-enabled');
const revealIO = new IntersectionObserver(
  (entries) => {
    for (const e of entries) {
      if (e.isIntersecting) {
        e.target.classList.add('reveal-in');
        revealIO.unobserve(e.target);
      }
    }
  },
  { rootMargin: '0px 0px -8% 0px', threshold: 0.08 },
);
const revealAll = () => {
  for (const el of document.querySelectorAll('.reveal:not(.reveal-in)')) {
    revealIO.observe(el);
  }
};

// "Scroll for more" hint: shows if the user lingers near the top after a result
// loads, and dissipates the moment they scroll.
const scrollHint = $('#scroll-hint');
let hintTimer;
const armScrollHint = () => {
  clearTimeout(hintTimer);
  scrollHint?.classList.remove('show');
  hintTimer = setTimeout(() => {
    if (window.scrollY < 140 && document.body.scrollHeight > window.innerHeight + 240) {
      scrollHint?.classList.add('show');
    }
  }, 2600);
};
window.addEventListener(
  'scroll',
  () => {
    clearTimeout(hintTimer);
    scrollHint?.classList.remove('show');
  },
  { passive: true },
);

let geminiHandle = null;

const startBigScore = () => {
  const box = $('#score-metal');
  if (!box) {
    return;
  }
  geminiHandle?.destroy();
  // Fast pulsing metal on the disc while loading; the number's canvas mirrors
  // the disc's clock so both render the same metal pattern. Orphaned instances
  // self-clean when their canvas leaves the DOM.
  geminiHandle = metal(box.querySelector('.bs-disc canvas'), { speed: 0.9, pulse: 0.7 });
  metal(box.querySelector('.bs-num canvas'), { sync: geminiHandle });
  requestAnimationFrame(() => $('#big-score').classList.add('in'));
};

const setBigScoreLoaded = async (report) => {
  const bs = $('#big-score');
  const ul = $('#big-stats');
  // Same rows as version C: label | track bar | number.
  ul.innerHTML = edStats(report);
  // Measure the list's natural width so the slide eases to the exact target —
  // easing toward an oversized max-width cap cuts the visible motion off
  // mid-curve, which reads as no easing at all.
  ul.style.maxWidth = 'none';
  const statsW = ul.offsetWidth;
  ul.style.maxWidth = '';
  await maskFontReady;
  // Digits sized to sit within the square box ("100" is the widest case).
  const q = [0, 80, 78, 55][String(report.overall).length] || 55;
  setMask($('#bs-num .bs-num-in'), scoreMaskUri(report.overall), `auto ${q}%`, 'center');
  geminiHandle?.setSpeed(0.16);
  geminiHandle?.setPulse(0);
  // Phase 1: stats ease in and the group re-centres (disc slides left).
  requestAnimationFrame(() =>
    requestAnimationFrame(() => {
      bs.classList.remove('loading');
      bs.classList.add('stats-in');
      ul.style.maxWidth = `${statsW}px`;
    }),
  );
  // Phase 2 (CSS): disc fades out to the metal number, which then inks to black.
  setTimeout(() => bs.classList.add('loaded'), 750);
};

// --- version A: gemini star (kept for the stakeholder A/B/C preview) ----------
// Four-point "gemini" spark: sharp tips with concave sides bowing inward.
const geminiPath = (() => {
  const c = 150;
  const R = 148;
  const d = 0.2 * R;
  const N = `${c},${c - R}`;
  const E = `${c + R},${c}`;
  const S = `${c},${c + R}`;
  const W = `${c - R},${c}`;
  const ne = `${c + d},${c - d}`;
  const se = `${c + d},${c + d}`;
  const sw = `${c - d},${c + d}`;
  const nw = `${c - d},${c - d}`;
  return `M${N} Q${ne} ${E} Q${se} ${S} Q${sw} ${W} Q${nw} ${N}Z`;
})();

const GEMINI_MASK = `url("data:image/svg+xml,${encodeURIComponent(
  `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 300'><path d='${geminiPath}' fill='#fff'/></svg>`,
)}")`;

const geminiShell = () => `
  <div class="gemini" id="gemini">
    <div class="gemini-star">
      <div class="gemini-metal"><canvas></canvas></div>
      <div class="gemini-score" id="gemini-score"></div>
    </div>
    <ul class="gemini-stats" id="gemini-stats"></ul>
  </div>`;

// A point on the star's right silhouette (N -> E -> S), used to hug the stats.
const geminiRightEdge = (() => {
  const N = [150, 2];
  const E = [298, 150];
  const S = [150, 298];
  const ne = [179.6, 120.4];
  const se = [179.6, 179.6];
  const q = (p0, cp, p2, t) => {
    const u = 1 - t;
    return [
      u * u * p0[0] + 2 * u * t * cp[0] + t * t * p2[0],
      u * u * p0[1] + 2 * u * t * cp[1] + t * t * p2[1],
    ];
  };
  return (s) => (s < 0.5 ? q(N, ne, E, s * 2) : q(E, se, S, (s - 0.5) * 2));
})();

const geminiStats = (report) => {
  const n = report.categories.length;
  const samples = [];
  for (let k = 0; k <= 240; k++) {
    samples.push(geminiRightEdge(k / 240));
  }
  const edgeX = (y) => {
    let bx = 0;
    let bd = Infinity;
    for (const [x, sy] of samples) {
      const dd = Math.abs(sy - y);
      if (dd < bd) {
        bd = dd;
        bx = x;
      }
    }
    return bx;
  };
  const top = 40;
  const bottom = 260;
  const gap = 52;
  return report.categories
    .map((cat, i) => {
      const y = top + (i / (n - 1)) * (bottom - top);
      const x = edgeX(y) + gap;
      return `<li style="--x:${x.toFixed(0)}px;--y:${y.toFixed(0)}px;transition-delay:${(0.15 + i * 0.09).toFixed(2)}s"><span class="gs-cat">${esc(cat.title)}</span> <span class="gs-sep">|</span> <span class="gs-num">${cat.score}</span></li>`;
    })
    .join('');
};

const startGemini = () => {
  const g = $('#gemini');
  if (!g) {
    return;
  }
  const metalEl = g.querySelector('.gemini-metal');
  metalEl.style.maskImage = GEMINI_MASK;
  metalEl.style.webkitMaskImage = GEMINI_MASK;
  geminiHandle?.destroy();
  geminiHandle = metal(g.querySelector('canvas'), { speed: 0.9, pulse: 0.7 });
  requestAnimationFrame(() => g.classList.add('in'));
};

const setGeminiLoaded = (report) => {
  const g = $('#gemini');
  $('#gemini-score').textContent = report.overall;
  $('#gemini-stats').innerHTML = geminiStats(report);
  geminiHandle?.setSpeed(0.16);
  geminiHandle?.setPulse(0);
  requestAnimationFrame(() => requestAnimationFrame(() => g.classList.add('loaded')));
};

// --- version C: editorial / typographic (no shader, deliberately restrained) --
const edStats = (report) =>
  report.categories
    .map(
      (cat, i) =>
        `<li style="transition-delay:${(0.12 + i * 0.07).toFixed(2)}s"><span class="es-cat">${esc(cat.title)}</span><span class="es-track"><span class="es-fill" style="--w:${cat.score}%"></span></span><span class="es-num">${cat.score}</span></li>`,
    )
    .join('');

const countUp = (el, to, ms) => {
  const start = performance.now();
  const tick = (now) => {
    const t = Math.min(1, (now - start) / ms);
    el.textContent = Math.round(to * (1 - (1 - t) ** 3));
    if (t < 1) {
      requestAnimationFrame(tick);
    }
  };
  requestAnimationFrame(tick);
};

const editorialShell = () => `
  <div class="editorial loading" id="editorial">
    <div class="ed-main">
      <span class="ed-figure"><span class="ed-num" id="ed-num">0</span></span>
      <span class="ed-bar"><span class="ed-bar-fill" id="ed-bar-fill"></span></span>
    </div>
    <ul class="ed-stats" id="ed-stats"></ul>
  </div>`;

const startEditorial = () => {
  const el = $('#editorial');
  if (!el) {
    return;
  }
  geminiHandle?.destroy();
  geminiHandle = null;
  requestAnimationFrame(() => el.classList.add('in'));
};

const setEditorialLoaded = (report) => {
  const el = $('#editorial');
  $('#ed-stats').innerHTML = edStats(report);
  countUp($('#ed-num'), report.overall, 900);
  $('#ed-bar-fill').style.setProperty('--w', `${report.overall}%`);
  requestAnimationFrame(() =>
    requestAnimationFrame(() => {
      el.classList.remove('loading');
      el.classList.add('loaded');
    }),
  );
};

// --- version registry: A/B/C differ only in the score hero --------------------
const SCORE = {
  a: { id: 'gemini', shell: geminiShell, start: startGemini, loaded: setGeminiLoaded },
  b: { id: 'big-score', shell: bigScoreShell, start: startBigScore, loaded: setBigScoreLoaded },
  c: { id: 'editorial', shell: editorialShell, start: startEditorial, loaded: setEditorialLoaded },
  d: { id: 'big-score', shell: bigScoreShell, start: startBigScore, loaded: setBigScoreLoaded },
};
let variant = (new URLSearchParams(location.search).get('v') || '').toLowerCase();
if (!SCORE[variant]) {
  variant = 'b';
}
const activeScore = () => SCORE[variant];
let lastReport = null;

const wireAccordion = () => {
  results.querySelectorAll('.check-btn').forEach((btn) => {
    btn.addEventListener('click', () => btn.closest('.check').classList.toggle('open'));
  });
};

const wireCopy = (report) => {
  const btn = $('#copy-md');
  const pre = $('#md-pre');
  if (!btn || !pre) {
    return;
  }
  const md = buildMarkdown(report);
  pre.textContent = md;
  btn.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(md);
      btn.textContent = 'Copied ✓';
    } catch {
      btn.textContent = 'Press Cmd/Ctrl+C';
      const range = document.createRange();
      range.selectNodeContents(pre);
      const sel = window.getSelection();
      sel.removeAllRanges();
      sel.addRange(range);
    }
    setTimeout(() => {
      btn.textContent = 'Copy report as Markdown';
    }, 2200);
  });
};

const renderResults = (report) => {
  lastReport = report;
  const s = activeScore();
  s.loaded(report);
  document
    .getElementById(s.id)
    .insertAdjacentHTML(
      'afterend',
      `<div class="post-tease" id="post-tease">${topFixes(report)}<div id="gate-slot">${leadGate(report)}</div></div>`,
    );
  revealAll();
  armScrollHint();
  wireLeadForm(report);
};

const wireLeadForm = (report) => {
  const form = $('#lead-form');
  if (!form) {
    return;
  }
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const email = $('#lead-email').value.trim();
    const errEl = $('#lead-error');
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      errEl.textContent = 'Enter a valid email address.';
      errEl.classList.remove('hidden');
      return;
    }
    errEl.classList.add('hidden');
    const btn = $('#lead-btn');
    btn.disabled = true;
    btn.textContent = 'Unlocking…';
    try {
      await fetch('/api/lead', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email,
          note: `AI Search Readiness: ${report.finalUrl} scored ${report.overall}/100 (${report.grade}).`,
        }),
      });
    } catch {
      // Never hold the report hostage to the CRM.
    }
    $('#gate-slot').innerHTML = fullReport(report);
    wireAccordion();
    wireCopy(report);
    const am = document.querySelector('.agent-metal');
    if (am) {
      metal(am, { speed: 0.18, feature: 760 });
    }
    revealAll();
  });
};

$('#analyze-form').addEventListener('submit', async (e) => {
  e.preventDefault();
  const url = $('#url').value.trim();
  const errEl = $('#form-error');
  const btn = $('#analyze-btn');
  if (!url) {
    errEl.textContent = 'Enter a URL to analyze.';
    errEl.classList.remove('hidden');
    return;
  }
  errEl.classList.add('hidden');
  results.innerHTML = activeScore().shell();
  results.classList.remove('hidden');
  activeScore().start();
  btn.disabled = true;
  const minLoad = new Promise((r) => setTimeout(r, 1200));
  const fail = (msg) => {
    geminiHandle?.destroy();
    geminiHandle = null;
    results.innerHTML = '';
    results.classList.add('hidden');
    errEl.textContent = msg;
    errEl.classList.remove('hidden');
  };
  try {
    const res = await fetch('/api/analyze', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url }),
    });
    const data = await res.json();
    if (!res.ok) {
      fail(data.error || 'Something went wrong. Try another URL.');
      return;
    }
    await minLoad;
    renderResults(data);
  } catch {
    fail('Network error. Please try again.');
  } finally {
    btn.disabled = false;
  }
});

revealAll();

// A/B/C version switcher (stakeholder preview). Tabs swap the score hero live;
// if a report is already on screen it re-plays the reveal in the new style.
const vtabs = Array.from(document.querySelectorAll('.vtab'));
const heroRobot = document.querySelector('.hero-robot');
const setActiveTab = () => {
  for (const t of vtabs) {
    t.classList.toggle('active', t.dataset.v === variant);
    t.setAttribute('aria-selected', t.dataset.v === variant ? 'true' : 'false');
  }
  // The waist-up llama is a version-B flourish; A and C keep a text-only hero.
  if (heroRobot) {
    heroRobot.style.display = variant === 'b' ? 'block' : 'none';
  }
};
setActiveTab();
for (const t of vtabs) {
  t.addEventListener('click', (e) => {
    e.preventDefault();
    const v = t.dataset.v;
    if (v === variant || !SCORE[v]) {
      return;
    }
    variant = v;
    history.replaceState(null, '', `?v=${v}`);
    setActiveTab();
    if (!lastReport) {
      return;
    }
    // Re-play the reveal in the newly selected style.
    results.innerHTML = activeScore().shell();
    results.classList.remove('hidden');
    activeScore().start();
    setTimeout(() => renderResults(lastReport), 850);
  });
}
