// Vanilla renderer for the AI Search Readiness tool. No framework, no build.
// All text taken from the analyzed page is escaped before it touches innerHTML.

const $ = (sel) => document.querySelector(sel);

const esc = (s) =>
  String(s ?? '').replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c],
  );

const ICONS = {
  pass: '<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/>',
  warn: '<path d="M12 9v4M12 17h.01"/><path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0Z"/>',
  fail: '<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6M9 9l6 6"/>',
  info: '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/>',
};

const statusIcon = (status) =>
  `<svg class="check-icon i-${status}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[status] || ICONS.info}</svg>`;

const EV_LABEL = {
  official: 'Official docs',
  study: 'Study',
  opinion: 'Vendor view',
  experimental: 'Experimental',
};

const evidenceBadge = (ev) =>
  `<a class="badge-ev ev-${ev.type}" href="${esc(ev.url)}" target="_blank" rel="noopener noreferrer">${EV_LABEL[ev.type]}<span class="src">&middot; ${esc(ev.source)}</span></a>`;

const READ_LABEL = {
  official: 'Read the guidance',
  study: 'See the study',
  opinion: 'Read the guide',
  experimental: 'See the docs',
};

const sourceLink = (ev) =>
  `<a class="read-more" href="${esc(ev.url)}" target="_blank" rel="noopener noreferrer">${READ_LABEL[ev.type]} at ${esc(ev.source)}<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10"/></svg></a>`;

const evidenceRow = (ev) => `<div class="ev-row">${evidenceBadge(ev)}</div>`;

const sswLink = (ssw) =>
  `<a class="ssw-link" href="${esc(ssw.url)}" target="_blank" rel="noopener noreferrer" title="SSW Rule: ${esc(ssw.title)}">Read the SSW rule<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10"/></svg></a>`;

const STATUS_WORD = { pass: 'PASS', warn: 'WARN', fail: 'FAIL', info: 'INFO' };

const buildMarkdown = (report) => {
  const out = [
    `# AI Search Readiness — ${report.finalUrl}`,
    '',
    `**Score: ${report.overall}/100 (Grade ${report.grade})** — ${report.passCount}/${report.totalScored} checks passed.`,
    '_Generated by the TinaCMS AI Search Readiness checker (tina.io). Fixes and sources included below._',
    '',
  ];
  for (const cat of report.categories) {
    out.push(`## ${cat.title} — ${cat.score}/100`, '');
    for (const ch of cat.checks) {
      out.push(`- **[${STATUS_WORD[ch.status]}] ${ch.label}** — ${ch.detail}`);
      if (ch.status !== 'pass') {
        out.push(`  - Fix: ${ch.fix}`);
      }
      out.push(`  - Why: ${ch.why}`);
      out.push(`  - Source (${ch.evidence.type}): ${ch.evidence.source} — ${ch.evidence.url}`);
    }
    out.push('');
  }
  return out.join('\n');
};

// A prompt the visitor can paste straight into their coding agent. Built from
// the same fix/why text the report already shows, so there is nothing to keep
// in sync.
const buildPrompt = (report, checks) =>
  [
    `I want to improve ${report.finalUrl} for search engines and AI answer engines.`,
    'Please make the following changes to this codebase:',
    '',
    ...checks.map(
      (c, i) =>
        `${i + 1}. ${c.label}\n   Problem: ${c.detail}\n   Fix: ${c.fix}\n   Why: ${c.why}${
          c.ssw ? `\n   Reference: ${c.ssw.url}` : ''
        }`,
    ),
    '',
    'Keep the existing behaviour and styling intact, and show me a diff for each file you change.',
  ].join('\n');

const COPY_ICON =
  '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect width="14" height="14" x="8" y="8" rx="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>';

const reportHeader = (report) => `
  <section class="report-head reveal">
    <div class="report-head-text">
      <h2>Your full report</h2>
      <p>All ${report.totalScored} checks, with the exact fix and the evidence behind each.</p>
    </div>
    <div class="report-head-actions">
      ${
        report.passCount < report.totalScored
          ? `<button class="btn btn-ghost" type="button" id="copy-prompt-all" data-label="Copy all fixes as a prompt">${COPY_ICON}Copy all fixes as a prompt</button>`
          : ''
      }
      <button class="btn btn-ghost" type="button" id="copy-md" data-label="Copy as Markdown">${COPY_ICON}Copy as Markdown</button>
    </div>
    <pre id="md-pre" hidden></pre>
  </section>`;

const blockerBanner = (report) =>
  report.blockers?.length
    ? `<div class="blockers reveal">
    <h3>This page is blocked from AI answers</h3>
    <p>Everything below still applies, but none of it can help until this is fixed. On presentation alone this page scored ${report.rawScore}.</p>
    <ul>${report.blockers.map((b) => `<li>${esc(b)}</li>`).join('')}</ul>
  </div>`
    : '';

const checkRow = (check) => `
  <div class="check" id="check-${check.id}">
    <button class="check-btn" type="button">
      ${statusIcon(check.status)}
      <span class="check-main">
        <span class="check-title">
          <span>${esc(check.label)}</span>
          <svg class="chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>
        </span>
        <span class="check-detail">${esc(check.detail)}</span>
      </span>
    </button>
    <div class="check-body">
      <div class="box">
        <p><strong>Fix:</strong> ${esc(check.fix)}</p>
        <p><strong>Why it matters:</strong> ${esc(check.why)}</p>
        <div class="link-row">
          <span class="lr-left">${evidenceBadge(check.evidence)}</span>
          ${check.ssw ? sswLink(check.ssw) : ''}
        </div>
        ${
          check.status === 'pass' || check.status === 'info'
            ? ''
            : `<button class="btn-prompt" type="button" data-prompt-check="${esc(check.id)}" data-label="Copy prompt for your coding agent">${COPY_ICON}Copy prompt for your coding agent</button>`
        }
      </div>
    </div>
  </div>`;

const category = (cat) => `
  <section class="card category reveal">
    <header class="cat-head">
      <div>
        <h3>${esc(cat.title)}</h3>
        <p>${esc(cat.blurb)}</p>
      </div>
      <div class="cat-score">${cat.score}<small>/ 100</small></div>
    </header>
    <div class="checks">${cat.checks.map(checkRow).join('')}</div>
  </section>`;

const TOOLS = [
  ['Google Rich Results Test', 'https://search.google.com/test/rich-results', 'Validate your structured data against Google itself.'],
  ['PageSpeed Insights / Lighthouse', 'https://pagespeed.web.dev/', 'Core Web Vitals and the experimental agentic-browsing audits.'],
  ['Schema Markup Validator', 'https://validator.schema.org/', 'Check your JSON-LD parses and matches your content.'],
  ['Semrush', 'https://www.semrush.com/', 'Full site audits, keyword and AEO tracking (paid).'],
];

const fullReport = (report) => `
  <div class="report">
    ${reportHeader(report)}
    <div class="report-cats">
      <section class="read-yourself reveal">
        <h3>If you&rsquo;d rather read it yourself</h3>
      </section>
      ${report.categories.map(category).join('')}
    </div>
    <section class="next reveal">
      <h3>Where to go next</h3>
      <p style="color:var(--text-2);font-size:0.875rem;margin-top:0.25rem;">This is a static, single-page check. To go deeper, these tools pick up where it stops.</p>
      <div class="tool-grid">
        ${TOOLS.map(
          ([name, href, note]) => `<a class="tool" href="${href}" target="_blank" rel="noopener noreferrer">
            <span><span class="name">${esc(name)}</span><span class="note">${esc(note)}</span></span>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><path d="M15 3h6v6M10 14 21 3"/></svg>
          </a>`,
        ).join('')}
      </div>
      <details class="refs">
        <summary>Sources &amp; further reading</summary>
      <ul>
        <li>${evidenceRow({ type: 'study', source: "GEO, Aggarwal et al. (KDD '24)", url: 'https://arxiv.org/abs/2311.09735' })}
          <p>In a controlled benchmark, adding <strong>citations</strong>, <strong>statistics</strong> and <strong>quotations</strong> improved a source&rsquo;s visibility in AI-generated answers by roughly <strong>30 to 40%</strong> (best single method +41%), tested on GPT-3.5-class engines and Perplexity. The same study found <strong>keyword stuffing did nothing</strong>. One study from 2023-24, so treat it as directional, not a traffic guarantee.</p></li>
        <li>${evidenceRow({ type: 'official', source: 'Google Search Central', url: 'https://developers.google.com/search/docs/appearance/ai-features' })}
          <p>Google states there are <strong>no special requirements</strong>, no AI-specific schema, and no machine-readable AI files needed to appear in AI Overviews. A page just has to be indexable and snippet-eligible.</p></li>
        <li>${evidenceRow({ type: 'experimental', source: 'Chrome Lighthouse, agentic browsing', url: 'https://developer.chrome.com/docs/lighthouse/agentic-browsing/scoring' })}
          <p>Lighthouse&rsquo;s agentic-browsing checks are experimental and reported as pass/fail, not a 0-100 score. It reports whether an <code>llms.txt</code> exists, but that file has <strong>no confirmed effect</strong>: Google has said it ignores it, so we score it as informational only.</p></li>
      </ul>
      </details>
    </section>
  </div>`;

const topFixes = (report) => {
  if (!report.topFixes.length) {
    return `<div class="card reveal" style="padding:1.5rem;background:var(--seafoam-100);color:var(--seafoam-800);">Nothing critical to fix. Every scored check passed. Unlock the full report below to see the detail and evidence.</div>`;
  }
  return `<div class="fixes reveal">
    <h3>Your 3 highest-impact fixes</h3>
    <ul class="fix-list">
      ${report.topFixes
        .map(
          (f, i) => `<li class="fix-item">
        <span class="fix-num">${i + 1}</span>
        <span><span class="lbl">${esc(f.label)}</span><span class="why">${esc(f.why)}</span>${sourceLink(f.evidence)}</span>
      </li>`,
        )
        .join('')}
    </ul>
  </div>`;
};

const leadGate = (report) => `
  <div class="gate reveal" id="gate">
    <div class="peek" aria-hidden="true"><span style="width:66%"></span><span style="width:50%"></span><span style="width:75%"></span><span style="width:40%"></span></div>
    <div class="inner">
      <span class="lock"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect width="18" height="11" x="3" y="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg></span>
      <h3>See your full report</h3>
      <p>Unlock all ${report.totalScored} checks with the exact fix and the evidence behind each one, plus where to go next. We&rsquo;ll email you a copy.</p>
      <form id="lead-form">
        <input type="email" id="lead-email" placeholder="you@company.com" aria-label="Your email" />
        <input type="tel" id="lead-phone" placeholder="Phone number" aria-label="Your phone number" autocomplete="tel" />
        <button class="btn" type="submit" id="lead-btn">Send report</button>
      </form>
      <p class="error hidden" id="lead-error"></p>
      <p class="microcopy">No spam. Unsubscribe anytime.</p>
    </div>
  </div>`;

// --- score reveal (replaces the loading spinner + summary card) ---------------

// --- interaction --------------------------------------------------------------

const results = $('#results');

// Scroll-triggered fade-ins. Elements with .reveal start hidden (only when JS is
// present, via .reveal-enabled) and animate in as they enter the viewport.
document.documentElement.classList.add('reveal-enabled');
const revealIO = new IntersectionObserver(
  (entries) => {
    for (const e of entries) {
      if (e.isIntersecting) {
        e.target.classList.add('reveal-in');
        revealIO.unobserve(e.target);
      }
    }
  },
  { rootMargin: '0px 0px -8% 0px', threshold: 0.08 },
);
const revealAll = () => {
  for (const el of document.querySelectorAll('.reveal:not(.reveal-in)')) {
    revealIO.observe(el);
  }
};

// "Scroll for more" hint: shows if the user lingers near the top after a result
// loads, and dissipates the moment they scroll.
const scrollHint = $('#scroll-hint');
let hintTimer;
const armScrollHint = () => {
  clearTimeout(hintTimer);
  scrollHint?.classList.remove('show');
  hintTimer = setTimeout(() => {
    if (window.scrollY < 140 && document.body.scrollHeight > window.innerHeight + 240) {
      scrollHint?.classList.add('show');
    }
  }, 2600);
};
window.addEventListener(
  'scroll',
  () => {
    clearTimeout(hintTimer);
    scrollHint?.classList.remove('show');
  },
  { passive: true },
);

// The five aspects are fixed, so we lay them out as placeholders before any
// analysis has run.
const CAT_TITLES = [
  'AI eligibility & crawlability',
  'Search fundamentals',
  'Structured data & entities',
  'Answer-engine content signals',
  'Agentic & AI-crawler readiness',
];

// --- editorial score view: typographic, no shader --------------------------
// Smooth score colour: 0 red -> ~33 red/orange -> ~54 yellow -> 75+ green.
// Interpolates hue across anchor stops so scores blend rather than snapping.
const lerp = (a, b, t) => a + (b - a) * t;
const scoreColor = (n) => {
  const t = Math.max(0, Math.min(100, n));
  const stops = [
    [0, 2],
    [33, 42],
    [75, 62],
    [100, 138],
  ];
  let hue = stops[stops.length - 1][1];
  for (let i = 1; i < stops.length; i++) {
    if (t <= stops[i][0]) {
      const [x0, h0] = stops[i - 1];
      const [x1, h1] = stops[i];
      hue = lerp(h0, h1, (t - x0) / (x1 - x0));
      break;
    }
  }
  return `hsl(${Math.round(hue)} 70% 44%)`;
};

const edStats = (report) =>
  report.categories
    .map((cat, i) => {
      const c = scoreColor(cat.score);
      return `<li style="transition-delay:${(0.12 + i * 0.07).toFixed(2)}s"><span class="es-cat">${esc(cat.title)}</span><span class="es-track"><span class="es-fill" style="--w:${cat.score}%;background:${c}"></span></span><span class="es-num" style="color:${c}">${cat.score}</span></li>`;
    })
    .join('');

// Placeholder rows reserve the stats height during loading so the hero doesn't
// jump when the real scores fade in.
const edStatsPlaceholder = () =>
  CAT_TITLES.map(
    (title) =>
      `<li><span class="es-cat">${esc(title)}</span><span class="es-track"><span class="es-fill" style="--w:0%"></span></span><span class="es-num">&ndash;</span></li>`,
  ).join('');

const countUp = (el, to, ms, colorize) => {
  const start = performance.now();
  const tick = (now) => {
    const t = Math.min(1, (now - start) / ms);
    const v = Math.round(to * (1 - (1 - t) ** 3));
    el.textContent = v;
    if (colorize) {
      el.style.color = scoreColor(v);
    }
    if (t < 1) {
      requestAnimationFrame(tick);
    }
  };
  requestAnimationFrame(tick);
};

const editorialShell = () => `
  <div class="editorial loading" id="editorial">
    <div class="ed-main">
      <span class="ed-figure"><span class="ed-num" id="ed-num">0</span></span>
      <span class="ed-bar"><span class="ed-bar-fill" id="ed-bar-fill"></span></span>
    </div>
    <ul class="ed-stats" id="ed-stats">${edStatsPlaceholder()}</ul>
  </div>`;

const startEditorial = () => {
  const el = $('#editorial');
  if (!el) {
    return;
  }
  requestAnimationFrame(() => el.classList.add('in'));
};

const setEditorialLoaded = (report) => {
  const el = $('#editorial');
  $('#ed-stats').innerHTML = edStats(report);
  countUp($('#ed-num'), report.overall, 900, true);
  const bar = $('#ed-bar-fill');
  bar.style.setProperty('--w', `${report.overall}%`);
  bar.style.background = scoreColor(report.overall);
  requestAnimationFrame(() =>
    requestAnimationFrame(() => {
      el.classList.remove('loading');
      el.classList.add('loaded');
    }),
  );
};

const urlParams = new URLSearchParams(location.search);
let lastReport = null;
// Deep-link from the report email: ?url=<page>&full=1 auto-runs the check and
// shows the full report ungated (the recipient already gave us their email).
const presetUrl = urlParams.get('url');
const autoFull = urlParams.get('full') === '1';

const wireAccordion = () => {
  results.querySelectorAll('.check-btn').forEach((btn) => {
    btn.addEventListener('click', () => btn.closest('.check').classList.toggle('open'));
  });
};

// Every copy button shares this: try the clipboard, and if it is unavailable
// fall back to selecting the text in the hidden <pre> so Cmd/Ctrl+C works.
const copyOut = async (btn, text) => {
  const pre = $('#md-pre');
  const label = btn.dataset.label;
  try {
    await navigator.clipboard.writeText(text);
    btn.textContent = 'Copied ✓';
  } catch {
    btn.textContent = 'Press Cmd/Ctrl+C';
    if (pre) {
      pre.textContent = text;
      const range = document.createRange();
      range.selectNodeContents(pre);
      const sel = window.getSelection();
      sel.removeAllRanges();
      sel.addRange(range);
    }
  }
  setTimeout(() => {
    btn.innerHTML = `${COPY_ICON}${label}`;
  }, 2200);
};

// Registered once, and reads lastReport rather than closing over a report, so
// analyzing a second URL cannot leave a stale handler behind.
results.addEventListener('click', (e) => {
  const btn = e.target.closest('#copy-md, #copy-prompt-all, [data-prompt-check]');
  if (!btn || !lastReport) {
    return;
  }
  if (btn.id === 'copy-md') {
    copyOut(btn, buildMarkdown(lastReport));
    return;
  }
  const failing = lastReport.categories
    .flatMap((c) => c.checks)
    .filter((c) => c.status === 'warn' || c.status === 'fail');
  const checks =
    btn.id === 'copy-prompt-all'
      ? failing
      : failing.filter((c) => c.id === btn.dataset.promptCheck);
  if (checks.length) {
    copyOut(btn, buildPrompt(lastReport, checks));
  }
});

const renderResults = (report) => {
  lastReport = report;
  setEditorialLoaded(report);
  document
    .getElementById('editorial')
    .insertAdjacentHTML(
      'afterend',
      `<div class="post-tease" id="post-tease">${blockerBanner(report)}${topFixes(report)}<div id="gate-slot">${autoFull ? fullReport(report) : leadGate(report)}</div></div>`,
    );
  revealAll();
  armScrollHint();
  if (autoFull) {
    // Arrived via the email deep-link — skip the gate, show the full report.
    wireAccordion();
  } else {
    wireLeadForm(report);
  }
};

const wireLeadForm = (report) => {
  const form = $('#lead-form');
  if (!form) {
    return;
  }
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const email = $('#lead-email').value.trim();
    const phone = $('#lead-phone').value.trim();
    const errEl = $('#lead-error');
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      errEl.textContent = 'Enter a valid email address.';
      errEl.classList.remove('hidden');
      return;
    }
    if ((phone.match(/\d/g) || []).length < 6) {
      errEl.textContent = 'Enter a valid phone number.';
      errEl.classList.remove('hidden');
      return;
    }
    errEl.classList.add('hidden');
    const btn = $('#lead-btn');
    btn.disabled = true;
    btn.textContent = 'Sending…';
    try {
      await fetch('/geo/api/lead', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email,
          phone,
          website: report.finalUrl,
          note: `AI Search Readiness: ${report.finalUrl} scored ${report.overall}/100 (${report.grade}).`,
          report: {
            url: report.finalUrl,
            overall: report.overall,
            grade: report.grade,
            passCount: report.passCount,
            totalScored: report.totalScored,
            categories: report.categories.map((c) => ({ title: c.title, score: c.score })),
            topFixes: report.topFixes.map((f) => ({ label: f.label, why: f.why })),
          },
        }),
      });
    } catch {
      // Never hold the report hostage to the CRM.
    }
    $('#gate-slot').innerHTML = fullReport(report);
    wireAccordion();
    revealAll();
  });
};

$('#analyze-form').addEventListener('submit', async (e) => {
  e.preventDefault();
  const url = $('#url').value.trim();
  const errEl = $('#form-error');
  const btn = $('#analyze-btn');
  if (!url) {
    errEl.textContent = 'Enter a URL to analyze.';
    errEl.classList.remove('hidden');
    return;
  }
  errEl.classList.add('hidden');
  results.innerHTML = editorialShell();
  results.classList.remove('hidden');
  startEditorial();
  btn.disabled = true;
  const minLoad = new Promise((r) => setTimeout(r, 2000));
  const fail = (msg) => {
    results.innerHTML = '';
    results.classList.add('hidden');
    errEl.textContent = msg;
    errEl.classList.remove('hidden');
  };
  try {
    const res = await fetch('/geo/api/analyze', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url }),
    });
    const data = await res.json();
    if (!res.ok) {
      fail(data.error || 'Something went wrong. Try another URL.');
      return;
    }
    await minLoad;
    renderResults(data);
    requestAnimationFrame(() =>
      results.scrollIntoView({ behavior: 'smooth', block: 'start' }),
    );
  } catch {
    fail('Network error. Please try again.');
  } finally {
    btn.disabled = false;
  }
});

revealAll();

// Deep-link: if a ?url= was passed (from the report email), prefill and run it.
if (presetUrl) {
  const input = $('#url');
  input.value = presetUrl;
  requestAnimationFrame(() => $('#analyze-form').requestSubmit());
}
